[project]
name = "ddns"
version = "0.1.0"
description = "Update a cloudflare dns record dynamically"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord>=2.3.2",
    "loguru>=0.7.3",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
